In [ ]:
import pandas as pd
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving Cosmetics_Customer_SkinType_Dataset.xlsx to Cosmetics_Customer_SkinType_Dataset.xlsx

In [ ]:
df = pd.read_excel("Cosmetics_Customer_SkinType_Dataset.xlsx")

In [ ]:
df.head()

,Customer_ID,Age,Gender,Skin_Type,Product_Category,Product_Name,Brand,Price_USD,Quantity,Purchase_Date,Rating,City
0,C001,30,Female,Normal,Haircare,Sunscreen,Nykaa,32.32,5,2025-05-28,3,Hyderabad
1,C002,35,Female,Sensitive,Skincare,Gentle Cleanser,Lakme,16.75,5,2025-05-16,5,Hyderabad
2,C003,21,Male,Oily,Makeup,Clay Mask,Mamaearth,34.04,1,2025-08-13,4,Chennai
3,C004,39,Female,Oily,Skincare,Oil Control Face Wash,Dot & Key,19.18,5,2025-03-24,5,Kochi
4,C005,40,Female,Oily,Skincare,Mattifying Moisturizer,Plum,6.61,1,2025-01-08,3,Chennai

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       200 non-null    object
 1   Age               200 non-null    int64
 2   Gender            200 non-null    object
 3   Skin_Type         200 non-null    object
 4   Product_Category  200 non-null    object
 5   Product_Name      200 non-null    object
 6   Brand             200 non-null    object
 7   Price_USD         200 non-null    float64
 8   Quantity          200 non-null    int64
 9   Purchase_Date     200 non-null    datetime64[ns]
 10  Rating            200 non-null    int64
 11  City              200 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 18.9+ KB

In [ ]:
df.isnull().sum()

Customer_ID         0
Age                 0
Gender              0
Skin_Type           0
Product_Category    0
Product_Name        0
Brand               0
Price_USD           0
Quantity            0
Purchase_Date       0
Rating              0
City                0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Revenue"] = df["Price_USD"] * df["Quantity"]

In [ ]:
df.to_excel("Cosmetics_Cleaned.xlsx", index=False)

In [ ]:
files.download("Cosmetics_Cleaned.xlsx")

In [ ]:
df.describe()

,Age,Price_USD,Quantity,Purchase_Date,Rating,Revenue
count,200.000000,200.000000,200.000000,200,200.000000,200.000000
mean,31.660000,21.630350,3.035000,2025-07-05 11:02:24,4.010000,66.258150
min,18.000000,5.050000,1.000000,2025-01-05 00:00:00,3.000000,5.840000
25%,25.000000,12.832500,2.000000,2025-04-20 18:00:00,3.000000,27.640000
50%,32.000000,20.785000,3.000000,2025-06-25 12:00:00,4.000000,55.010000
75%,39.000000,31.662500,4.000000,2025-09-23 06:00:00,5.000000,96.650000
max,45.000000,39.780000,5.000000,2025-12-30 00:00:00,5.000000,186.400000
std,8.169954,10.320003,1.408437,NaN,0.820528,46.161716

In [ ]:
df.groupby("Brand")["Revenue"].sum().sort_values(ascending=False)

Brand
Maybelline    2742.99
Nykaa         2260.67
Dot & Key     2196.07
Lakme         1651.42
Minimalist    1645.40
Mamaearth     1549.87
Plum          1205.21
Name: Revenue, dtype: float64

In [ ]:
df.groupby("Product_Category")["Revenue"].sum()

Product_Category
Haircare    4868.28
Makeup      3808.57
Skincare    4574.78
Name: Revenue, dtype: float64

In [ ]:
df.groupby("Brand")["Rating"].mean().round(2)

Brand
Dot & Key     4.15
Lakme         4.21
Mamaearth     3.83
Maybelline    4.00
Minimalist    4.00
Nykaa         4.09
Plum          3.77
Name: Rating, dtype: float64

In [ ]:
df.to_excel("Cosmetics_Cleaned.xlsx", index=False)

In [ ]:
files.download("Cosmetics_Cleaned.xlsx")